BT-EscapeRooms/BT-EscapeRooms/Controllers/ApiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BT_EscapeRooms.Code;
using BT_EscapeRooms.Data;
using BT_EscapeRooms.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BT_EscapeRooms.Controllers
{
    [Produces("application/json")]
    [Route("api")]
    public class ApiController : Controller
    {
        ApplicationState state;
        EscapeRoomContext context;

        public ApiController(EscapeRoomContext _context, ApplicationState _state)
        {
            state = _state;
            context = _context;
        }
        [HttpGet("Scores")]
        public ActionResult GetScores(string username)
        {
            var scoresList = context.Scores.Where(w => string.IsNullOrEmpty(username) ? true : w.Username == username);

            return Json(scoresList);
        }

        [HttpPut("Username")]
        public ActionResult UpdateUsername(string username, string newUsername)
        {
            if (string.IsNullOrEmpty(username))
            {
                return NotFound();
            }
            var scores = context.Scores.Where(w => w.Username == username).ToList();
            foreach(var score in scores)
            {
                score.Username = newUsername;
            }
            var result = context.SaveChanges();
            return Json(result);
        }

        [HttpDelete("Scores")]
        public ActionResult DeleteScores(string username)
        {
            if (string.IsNullOrEmpty(username))
            {
                return NotFound();
            }
            var scores = context.Scores.Where(w => w.Username == username).ToList();
            foreach (var score in scores)
            {
                context.Remove(score);
            }
            var result = context.SaveChanges();
            return Json(result);
        }

        [HttpGet("NewGame")]
        public ActionResult NewGame(string username, Code.Difficulty difficulty)
        {
            var userID = Guid.NewGuid();
            var map = new Map(username, difficulty);
            state.AddGame(userID, map);
            return Json(new { User = userID, Map = map.ToString(), FullMap = map });
        }
        [HttpPost("Move")]
        public ActionResult Move(Guid user, string direction)
        {
            var map = state.GetGame(user);
            if (map == null)
            {
                return NotFound();
            }
            if (!map.GameEnd)
            {
                map.Move(direction);
            }
            return Json(new { User = user, Map = map.ToString(), FullMap = map });
        }
        [HttpPost("Attack")]
        public ActionResult Attack(Guid user)
        {
            var map = state.GetGame(user);
            if (map == null)
            {
                return NotFound();
            }
            if (!map.GameEnd)
            {
                map.PlayerAttack();
                map.MonsterAttack();
                if (map.CurrentAction == GameAction.Victory || map.CurrentAction == GameAction.GameOver)
                {//save score
                    SaveScore(map);
                }
            }

            return Json(new { User = user, Map = map.ToString(), FullMap = map });
        }
        [HttpPost("AttackWithPotion")]
        public ActionResult AttackWithPotion(Guid user)
        {
            var map = state.GetGame(user);
            if (map == null)
            {
                return NotFound();
            }
            if (!map.GameEnd)
            {
                map.UseToxicPotion();
                if (map.CurrentAction == GameAction.Victory || map.CurrentAction == GameAction.GameOver)
                {//save score
                    SaveScore(map);
                }
            }

            return Json(new { User = user, Map = map.ToString(), FullMap = map });
        }
        [HttpPost("Heal")]
        public ActionResult Heal(Guid user)
        {
            var map = state.GetGame(user);
            if (map == null)
            {
                return NotFound();
            }
            if (!map.GameEnd)
            {
                map.UseHealingPotion();
            }

            return Json(new { User = user, Map = map.ToString(), FullMap = map });
        }
        [HttpGet("Name")]
        public ActionResult Name()
        {
            return Json(HttpContext.User.Identity.IsAuthenticated);
        }


        private void SaveScore(Map map)
        {
            context.Add(new Score
            {
                Date = DateTime.Now,
                Difficulty = map.Difficulty,
                Points = map.CurrentPlayer.Score,
                Username = map.CurrentPlayer.Username
            });
            context.SaveChanges();
        }
    }
}

BT-EscapeRooms/BT-EscapeRooms/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BT_EscapeRooms.Models;

namespace BT_EscapeRooms.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Backend()
        {
            return View();
        }
    }
}

BT-EscapeRooms/BT-EscapeRooms/Views/Home/Backend.cshtml
@{
    ViewData["Title"] = "Backend";
}

<h2>Backend</h2>

<div>
    <h2>Search by username</h2>
    <input class='game-input' type="text" id="txtUsernameFilter" name="txtUsernameFilter" placeholder="Username to search" />
    <span class="game-button" id="btnSearch" name="btnSearch">SEARCH</span>
</div>
<table id="tblScores" class="sortable api-source" data-url="@Url.Action("Scores","Api")" data-method="GET">
    <thead>
        <tr>
            <th data-source="username">Username</th>
            <th data-source="date" data-type="date">Date</th>
            <th data-source="difficulty">Difficulty</th>
            <th class="sortable" data-source="points" data-type="int">Score</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

<div>
    <h2>Delete user scores</h2>
    <input class='game-input' type="text" id="txtUsernameDelete" name="txtUsernameDelete" placeholder="Username to delete" />
    <span class="game-button" id="btnDelete" name="btnDelete">DELETE</span>
</div>

<div>
    <h2>Update user name</h2>
    <input class='game-input' type="text" id="txtUsernameOld" name="txtUsernameOld" placeholder="Old username" />
    <input class='game-input' type="text" id="txtUsernameNew" name="txtUsernameNew" placeholder="New username" />
    <span class="game-button" id="btnUpdate" name="btnUpdate">UPDATE</span>
</div>

BT-EscapeRooms/BT-EscapeRooms/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="game">

</div>